name: NPM Docker Container Creation

on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master, develop ]
  
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.githubDockerToken}}
          registry: docker.pkg.github.com
          repository: terryyoung22/react-site/reactapp
          tag_with_ref: false


    ##############docker hub push##################

    # - name: Docker login
    #   run: docker login -u ${{ secrets.DockerHubUser }} -p ${{ secrets.DockerHubToken }}

    # - name: Docker build and push React app
    #   run: docker build -f ${GITHUB_WORKSPACE}/ReactApp/Dockerfile -t ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:latest . && docker push ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:latest
    #   env:
    #     IMAGE_NAME: react
