name: NPM Docker Container Creation

on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master, develop ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    ##############docker hub push##################

    - name: Docker login
      run: docker login -u ${{ secrets.DockerHubUser }} -p ${{ secrets.DockerHubToken }}

    - name: Docker build and push React app
      run: docker build -f ${GITHUB_WORKSPACE}/ReactApp/Dockerfile -t ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:latest . && docker push ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:latest
      env:
        IMAGE_NAME: react
