name: NPM Docker Container Creation

on:
  push:
    branches: [ master,develop ]
  pull_request:
      branches: [ master, develop ]
  

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.githubDockerToken}}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: react-site/ReactApp/
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ${{ github.repository_owner }}/react:latest



    ##############docker hub push##################

    # - name: Docker login
    #   run: docker login -u ${{ secrets.DockerHubUser }} -p ${{ secrets.DockerHubToken }}

    # - name: Docker build and push React app
    #   run: docker build -f ${GITHUB_WORKSPACE}/ReactApp/Dockerfile -t ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:latest . && docker push ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:latest
    #   env:
    #     IMAGE_NAME: react
