name: NPM Docker Container Creation

on:
  push:
    branches: [ master,develop ]
  pull_request:
      branches: [ master, develop ]
  

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparation
      id: prep
      run: |
        REGISTRY="ghcr.io"
        IMAGE="${REGISTRY}/${{ github.repository }}/${{ github.event.repository.name }}"
        TAGS="${IMAGE}:latest"
        if [[ $GITHUB_REF == ref/head/master ]]; then
          TAGS="${TAGS},${IMAGE}:latest"
        fi
        echo ::set-output name=tags::${TAGS}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.githubDockerToken}}
    - name: Build, tag, and push image to Amazon ECR
      env:
        GITHUB_REGISTRY: ${{ steps.prep.outputs.REGISTRY }}
        GIT_IMAGE: ${{ steps.prep.outputs.image }}
        TAG: latest
      run: |
        docker build -t $GITHUB_REGISTRY/${{ github.repository }}:$TAG .
        docker push $GITHUB_REGISTRY/${{ github.repository }}:$TAG



    ##############docker hub push##################

    # - name: Docker login
    #   run: docker login -u ${{ secrets.DockerHubUser }} -p ${{ secrets.DockerHubToken }}

    # - name: Docker build and push React app
    #   run: docker build -f ${GITHUB_WORKSPACE}/ReactApp/Dockerfile -t ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:latest . && docker push ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:latest
    #   env:
    #     IMAGE_NAME: react
